version:
  name: velociraptor
  version: 0.76.6
  commit: 20c779e55
  build_time: '2026-06-03T10:53:44Z'
  compiler: go1.25.3
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://127.0.0.1/velociraptor/
  ca_certificate: '-----BEGIN CERTIFICATE-----

    MIIDTDCCAjSgAwIBAgIRAKzPdIm6zZ6+d3Sy3YPUxU0wDQYJKoZIhvcNAQELBQAw

    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDcwMTE0NDM1M1oXDTM2

    MDYyODE0NDM1M1owGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq

    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0oXg6KnEV40Q0zGLyQNHpoIHtFrAg7/w

    DcvFBrzHxksezgzBll6D2/SSFiQk+qR4tD/X6nDLAEaLFFPy4Pjk6VCVI3TQYFhx

    mI9C6E9fDsfjlOhiRjSHMnbZ+G3kLRQUauEkKIzuSJyNpEzDtlzQfef+x6fFL9W+

    jsWyo0XfS3cGq3737f7sPZlCeUHcZlkcjOrwJMadfs8rbfBgIvMG5jm36O2ziE2F

    w63MhgbpKPMSw/SXFfGoaJrII0ijGTB1A+3LtzzNzg58+djfdhzeWzu8vwFwcCla

    vv16xvMZGio/lrxselpGm+cEf9t84gbU2H1J3vtkdtCBhkSvMmRZEQIDAQABo4GM

    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH

    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUevjE6F5iUbTmrbMDsz1sZlR0

    POwwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ

    KoZIhvcNAQELBQADggEBAATbfyN1rlNuIs/9q1TuGrAW1IMZiQN8j0b4w5kFB3MH

    scgGMEFFaAMv5IZjo58/K1QevrLpgbjINUyZ5LgOTgU4iR3VJmDKCxWLgAamyB7g

    Cr9ll/Pt8vz5hBNZKZWH5Z9h6h716cs3asCrOHd+QGxhGsTn4Dy3bM6JsHhMTzDj

    tPC+2M3t5Ndx1aqVuNVRgvTJS1IhjyOhIZ8o2EpOID9OiDKMvQH49RQhg9T3c5E6

    cqchm4wz+iqUuuhrGw2KIcTfL8xzEV3umfkdthLrGtlS7C2YhtuOv0BhR7/p/MO4

    +yELBymDiVAPC8vJvMmXZV1MEF4LsdtCsjOUCvtLifI=

    -----END CERTIFICATE-----

    '
  nonce: KJ7BE4aj6Pc=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/bin/velociraptor
  server_version:
    version: 0.76.6
    commit: 20c779e55
    build_time: '2026-06-03T10:53:44Z'
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  bind_address: 0.0.0.0
  bind_port: 8002
  bind_scheme: tcp
GUI:
  bind_address: 0.0.0.0
  bind_port: 8000
  gw_certificate: '-----BEGIN CERTIFICATE-----

    MIIDQTCCAimgAwIBAgIQdGKzlV3K3C0ENad9ckTONzANBgkqhkiG9w0BAQsFADAa

    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzAxMTQ0MzUzWhcNMjcw

    NzAxMTQ0MzUzWjApMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxEDAOBgNVBAMMB0dS

    UENfR1cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvFVK8Wf9JOcxj

    kPrz3FQQ0JPFtrnA4lmFOvv05WKRgnBIpa47lmu58waSlKo4sc1QTARMUiotjAhZ

    OIcvkAaz7oplnthg+ExP9HfSAMMQDwqean2+a6mM+Ven7oaBGxoXe/fKok4byGm4

    5GXOIh/6rJCqIqwgs2uZexHEzdfjWqQHHNOU7kjkewLIxhWp/t1e6jq1Z7orIKpj

    wlfWxM/M4XJA0A2kp7zmZCmdAZnJQo5cSd6NrTb+hvXEjfNUhYO3HfE2VWWfi8at

    ck3FT8rv3Tqv5fmjPpgvfrMUV3UG0sC1iell4t5g2S8fNRe5mpuh4Rd07QTSjLz9

    8MMbEop9AgMBAAGjdDByMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF

    BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBR6+MToXmJR

    tOatswOzPWxmVHQ87DASBgNVHREECzAJggdHUlBDX0dXMA0GCSqGSIb3DQEBCwUA

    A4IBAQClJjkg7uF7mfb6BPur1LV1dV7zBm2A0QBgnyMB0sPuqgzsdgiLHozVQTQl

    u6g+iYxbPH/AOybGgIjw+qimKJUC30Rd89KYLf/Ry3wr5rXoh8qcWbALVjEgSaDf

    i/VJRDDUv8tT/aQTOUqAuvDk2kFPTlZE+Q6xJm34FnasXMaWSdNv8LgnTsHS+SUY

    N+o42XsNoU/JtcrSNlFCpNc3UhVP5fUpoOd4FBNqRkdsIFhpiGRb9oBu9g4fUdl/

    vPnQQzo5+GX7YK35ycq7iVT1Mq6NC6fDaYsi/tfF5ioc2ViQYlKiPdPAUbUc8veW

    EiNl7OJtJQHsozVzKwuDoU5nBVVY

    -----END CERTIFICATE-----

    '
  gw_private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEpAIBAAKCAQEArxVSvFn/STnMY5D689xUENCTxba5wOJZhTr79OVikYJwSKWu

    O5ZrufMGkpSqOLHNUEwETFIqLYwIWTiHL5AGs+6KZZ7YYPhMT/R30gDDEA8Knmp9

    vmupjPlXp+6GgRsaF3v3yqJOG8hpuORlziIf+qyQqiKsILNrmXsRxM3X41qkBxzT

    lO5I5HsCyMYVqf7dXuo6tWe6KyCqY8JX1sTPzOFyQNANpKe85mQpnQGZyUKOXEne

    ja02/ob1xI3zVIWDtx3xNlVln4vGrXJNxU/K7906r+X5oz6YL36zFFd1BtLAtYnp

    ZeLeYNkvHzUXuZqboeEXdO0E0oy8/fDDGxKKfQIDAQABAoIBAALRnxFi90POQrRx

    9WYYSAWi/zBa3H2bXi9RhBRj3jKurznTDsR/ZzLkpeq6PN/tXzJJwnSG+Gm6vpQ8

    li5Q/5hXvERnJgQeO0e61nQprUNyWoyOYu9Qe9xYU+3RFZZwQY1I9M9/O8D9CwtH

    TYaWp8bdsz6OkOwHAJ+g0+gfiW8iwZyDdCwfdqnmnI2Id0MKq6MRkp7lMCstSzSs

    RuP7eWDCdH7ww2QSytYCFd46zLH1K4v6w75ujLI8KFjFWYx/GtFIYpXbUnm+pAwj

    bRuq8JMgwzGwq+Fz0vGyvv0YPmU3fYVmdEKv88mdnbdeDUjiADIfDUb6EqRdW1Qn

    RtZDmIECgYEA5rm8s7ulMXG+XiRRW96x8ssUsg/msFxe8zz2trbsYzPfiJ06q6dw

    mQl1DMnPY2DYyfQHkhYYFXl4jZOcPcTWvyCZVtnu5mojQXnYLfnhLp3FCgvG1kR8

    3M+8E0sy31teeItAyMdYJeKV+cDzllSFCBQzTYnWBa0yp5EeatlkTZECgYEAwkM0

    SUQyTWUeNJXtxi7uISBmR9tpjtBphDWMKyXJrPCHvi7jomSHDcN6Vn4MI6Vyny47

    S42OIheH7ExmOnxSh8TytzV2+91ye8r8mm8ntNf5Zyfc5xnJDZC0zSjsARvH6UHu

    DbH4IbAKY6S92Lg77RXv7XkB8kjp2/BQZ/cOaC0CgYEAsL7AC39HgKT9i+iOWq4x

    6yge5ni/44IfSn39EOL4GtZ1+pVXiH9wBgv0mqNON3bNG4fQ9Nvv/yNacjoNilPr

    neY/EQVJuUC9WT8Zl76//ZHmi1eSLjmw3QZVsQH+KpQ3vmgObMAoin0VHontD9AX

    SKUQ1+krBpYzI6JLhtaZu8ECgYBTVOLL/w4Y9yRy6FG8LwuFeFGHx45LbgmlZhb/

    t1EA95kzMwgA9GCevdjv21g3vlQiBoH3Ef0DkNaEve0ob4YzqX94qd2lg0QF6Hhd

    gwskX3UkFAyFsiD1ybpVO5WpkBI8dES66ToIsWxzfArYOYezVzK5yqvUFAUFjNvh

    DTDH7QKBgQDJmNUMz2uPxXxzdt0yMymDoGJNT4yAmQhznPmNsBiAX/q8XS2+9mH/

    M6bpuZHMjSw0O4R2qe8wycqsAm99OVoVMpYtzAD2atY78++HixOcXDw/S51A02Jm

    1Xu3baW3DYTdiUlPqWFueHhSvj/u1Q7oQJKoBuyUFtNWbEY/seKKYw==

    -----END RSA PRIVATE KEY-----

    '
  public_url: https://127.0.0.1/velociraptor/app/index.html
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MyIgaGVpZ2h0PSI2MyIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNTMgNjMiPjxwYXRoIGQ9Ik0yNyAzYy0zIDItMTMgOC0yMyAxMGw2IDMyYTEwMyAxMDMgMCAwIDAgMTcgMTZsNi01IDExLTExIDYtMzJDMzkgMTEgMzAgNSAyNyAzeiIgZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PHBhdGggZD0iTTI2IDBDMjMgMiAxMiA4IDAgMTBjMSA3IDUgMzIgNyAzNWExMTMgMTEzIDAgMCAwIDE5IDE4bDctNiAxMi0xMmMyLTMgNi0yOCA4LTM1QzQwIDggMjkgMiAyNiAwWm0wIDU1LTYtNC04LTktNS0yNnYtMWwyLTFjOC0xIDE2LTYgMTYtNmwxLTEgMSAxczggNSAxNyA2bDEgMXYxcy0zIDIzLTUgMjZsLTggOWMtMiAyLTQgNC02IDR6IiBmaWxsPSIjYWIwMDAwIiBmaWxsLW9wYWNpdHk9IjEiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjxwYXRoIGQ9Ik0zOSAxOWExMzQ3IDEzNDcgMCAwIDEtMTMgMjZoLTJMMTQgMTloM2wyIDEgMSAxdjFhMjUwIDI1MCAwIDAgMSA2IDE3IDUyODkgNTI4OSAwIDAgMCA5LTIwaDR6IiBmaWxsPSIjMDAwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS13aWR0aD0iMSIvPjwvc3ZnPg==
    type: sidebar
    new_tab: true
  authenticator:
    type: Basic
  base_path: /velociraptor
CA:
  private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEpAIBAAKCAQEA0oXg6KnEV40Q0zGLyQNHpoIHtFrAg7/wDcvFBrzHxksezgzB

    ll6D2/SSFiQk+qR4tD/X6nDLAEaLFFPy4Pjk6VCVI3TQYFhxmI9C6E9fDsfjlOhi

    RjSHMnbZ+G3kLRQUauEkKIzuSJyNpEzDtlzQfef+x6fFL9W+jsWyo0XfS3cGq373

    7f7sPZlCeUHcZlkcjOrwJMadfs8rbfBgIvMG5jm36O2ziE2Fw63MhgbpKPMSw/SX

    FfGoaJrII0ijGTB1A+3LtzzNzg58+djfdhzeWzu8vwFwcClavv16xvMZGio/lrxs

    elpGm+cEf9t84gbU2H1J3vtkdtCBhkSvMmRZEQIDAQABAoIBAAVUgasOXPk0/4Au

    CiqeQu6wrofW1OE5EgzoCU6NfMw01nGz1w/AMpvg7jUcjZRMJ1NepZrgUnQeNR2q

    2Z9FJKGSH7EzPyaIqA6gu5pPY89yCOgaIUktrF8fF890s9EJh+dOrjhPHNDZPYj+

    LxCDetK3QHHXD0oR4guyGR7jETSzQd+muKOsO6t/l1ZuyG6I1BC+IRCQwMYr6dfI

    ITpBsXv4v3O5okh4xfN/fsWT3oz7xnJOkacm3Z+1v3RZ0luh2sXVvNBJTXHX19NS

    fJQ1mryFTk5Slc+XTWHWYjAR59+BTFKivrhH/tfE5fiVCIotaNJTUPMuJBMYMJZR

    4ceIrGkCgYEA2ULmVq2QzjxhMm2C/N5xRDVFa/Ebbzb7VKDrWkgRik8jAP2CErL8

    i9GrS5lSR9zekG/0zG5ViGSry0VFtH/i+V/+9y0Cz3mihTHuUi5xbSTFYCjy2dfy

    6vX7uYPviPOMVED6ujdydYRCyFi7QnRfO/+5Eap/38SXbaD1432nEmkCgYEA+A9m

    VXoF4otj6shtdwat8QeM3GOtwE7UzrqPs8mm5I7F6GqYDdFUEuqlBkcmvatZz+Z+

    oYygddYXwd76ZR1Fhr7FJQHulzon3VjtCsWETSYt0vjNRiDU8MhUVlg4RA7oduGL

    qxH/MNQ1YMDD275Or3U5+M7nzGAnu0Cdo14d7GkCgYBvluHx8THoC7Esknzt3l60

    1tuyRmN96vKKFCDt/QgtTto+vvaZHh+CvQ1LRhOx32rdKvPEMIN0C6kFPa5AuFLf

    HQQ69n50DBiCaxPqV/pgQbuy2TVq2HTnY7KIJZDZeaZA/CMLlEEQxP78Ij8EMftc

    OMtYnIcTaskQQNUqpDY0yQKBgQDcP2ggKsjA3fyoQK8YyKB2arrCD+r83cGLkA/5

    lOkO9El6U/KQCjV42kgN6+zU6ShENKZor+Dk32OWqnFuh+/sdMO8WRvLwEIXAVbu

    gnM2wNhdArXYN1x6MZTYWVoT65yxuQ72pHMNms2OC3mbSTy6Av6nEKa1Swbb9sJA

    hFdTSQKBgQCvaysPZ56gskClQ3yeP262zFhGTbl+5Z/fCC2nCEWUpEDaLZASwr/k

    rwqeh7V7EBB/biB4GwAFBunzskG8i8seX7F7736UmGGowv2hN8xb0GjzIHTPTsM8

    nFXHDFACgnHGjYWGRYxays33R8iy/n03BJosFvBOfHR9PZAoP26P7g==

    -----END RSA PRIVATE KEY-----

    '
Frontend:
  hostname: 127.0.0.1
  bind_address: 0.0.0.0
  bind_port: 8001
  certificate: '-----BEGIN CERTIFICATE-----

    MIIDWDCCAkCgAwIBAgIRALXjkemCJ3c+dfADUMfTMMowDQYJKoZIhvcNAQELBQAw

    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDcwMTE0NDM1M1oXDTI3

    MDcwMTE0NDM1M1owNDEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRswGQYDVQQDExJW

    ZWxvY2lyYXB0b3JTZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB

    AQC1GhbCqiZ7ikvlNKgl6KAFB0jVBrPIOSaxnf2RFKh3r+JVaFyNmnoPr4fGfKMc

    iZjyn4Ikgw/19kslaGS7MQIUHyW1LdzSLF4SjAMUEUjejFIFU2ZBWBYdb+wUweVN

    7IX82lijpDxXWHsj+fsaay7Am+gX02qdLApetJJkTvIO7lAChOhh9rHNFXj1/C9W

    3u/J+JyoRu7OvzQoGNGmsE4AmZBuKhXFZ9vv7xnyQELLwFB1kGkoF+wH0Az/aCnJ

    7pagjrONohqcX+0QlP9+ha8O/zHCXOH9YgwXtVTD1dYo0BUCp8L8IhJV8MRtzDZG

    hCps8IIYuykZx6kv+IvfEMhzAgMBAAGjfzB9MA4GA1UdDwEB/wQEAwIFoDAdBgNV

    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSME

    GDAWgBR6+MToXmJRtOatswOzPWxmVHQ87DAdBgNVHREEFjAUghJWZWxvY2lyYXB0

    b3JTZXJ2ZXIwDQYJKoZIhvcNAQELBQADggEBAKS+m0qu7TIJIPDdW9ovwClWw1KI

    DDJiVQDFhvFv0yU29CULmcwikGz/um916hlv0EwV5JEg5encMmuvc8r6NjY1H3z9

    jMC9SnTtHf9Vq9zALNT2jCqlM9co4g+/9dvLHhNKlccyM4L9RJQ6P2RJ9AqowazI

    FYUGSaJ0VYW7AaiXc3CidaMoAN2vyUYq+W6T0drEQpZLbpwojezK+lQcuLv0QHRu

    2+77uok9a1baffbaIMtJHLR7l097sqpoyfp4Jb8HDc45KvHW/7u6LT1CGDNeui29

    wAYwzRoNnF+p8F2xufPwu4loOi7MaAYMAKXP2K7nO9hKkCDfVN6tNopaRIk=

    -----END CERTIFICATE-----

    '
  private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEowIBAAKCAQEAtRoWwqome4pL5TSoJeigBQdI1QazyDkmsZ39kRSod6/iVWhc

    jZp6D6+HxnyjHImY8p+CJIMP9fZLJWhkuzECFB8ltS3c0ixeEowDFBFI3oxSBVNm

    QVgWHW/sFMHlTeyF/NpYo6Q8V1h7I/n7GmsuwJvoF9NqnSwKXrSSZE7yDu5QAoTo

    YfaxzRV49fwvVt7vyficqEbuzr80KBjRprBOAJmQbioVxWfb7+8Z8kBCy8BQdZBp

    KBfsB9AM/2gpye6WoI6zjaIanF/tEJT/foWvDv8xwlzh/WIMF7VUw9XWKNAVAqfC

    /CISVfDEbcw2RoQqbPCCGLspGcepL/iL3xDIcwIDAQABAoIBADCxEYKIRe18WviG

    xlje6TtA4KOp+CdyukUSIe1ifQMlDnkBJLVL3dqeyqYit6ZCFpXRLigL9vweGsk1

    frPXsuPfFf/XE2KM3EQnUeKQ3SM83gahjEIwYU3L3FEear0fRU0dFaz1yOWBHCap

    nQpW3AycPnQ9exJEF4usCBohIbLCitDgvFB6I8ySgOrrGKqD15mEJHs9fgd5t/QY

    XZhfbz29Rln0KDD7EXe+u0YdHDwnVvuUXV6sc4jeL0k2pJH1f/xpSHNbYJu/qEwY

    tBjOG5vCyDWMexLt6pzOpPB+vRjiUa/YHsPtCzriVriSWlW3VgR6/MjvHQBAwUs4

    J3iTLq0CgYEA8Idu8emSJGzX+mT1egr0BVkZr3ZnnlApdQ+NQR2Gjxl6dPyYW447

    XAJNN2t9O0OkSpekhG2RG9CvFlmZN9AjHI7PD4NbCc8PNcZVfnmwusIov9L5hkwV

    QyoOVxSp1V3F2zJmu2Y9ULc52uhea8VYZbch7zdBPpaUWaAUFLbddCUCgYEAwMAf

    5555BNkmRyfj6T+8P5v1e2xv7XJZK7idq/C+ah55mMrgQl/7D1PcBxyLoIce1Qt/

    6wxIAON4ZNkcErUCK5hB0YUJ92WkodIIHk/Y0fTkC1C2RU4vuioB4pgCxRCGHA6C

    9z2BOBYwWstROrM9twqf2nijy6YJQACc4W/rGrcCgYBbbS9ntr+9Jr5FyEBivm0Y

    51BTGK+0RoYrn9iyapWuKSIZ+7Wx/3NiuuE88pesgj6dt9xqFfe1WfJjjXUm+O+P

    uFzOacCeDt2aNCRlKb5ajtjMaVY9jQf7+q1uvkT7/GPruNHB48/ksXDFW9QgJOg/

    6Yd1lUwwjS4gjy9y3Dt7HQKBgQConmpKwYO1DhJCZU8oGa2hJ9pUosQ3wLTpXpPw

    eqbZRtexJqmQ505GVmJBhmNPh2UdkvXQtem3fUcxUg0RAHBpmsTZeb0CRFUFiyu2

    +LsA0W89xtntPzzZay5DACBMLOxlVvyTNab5Xc/nXb4tz+fJXO4CvU7tNM8awm57

    eOD/eQKBgFI0O1FR+pgt7GkuihmvX92+XIys5oz0Q1+0GQpoKr0QOjxcs7D/Wmyn

    OQbPWmhVii3ky1Duxd+sJpJEzCtci9Hz0Eps3AjRRHtYzUs8stBR+p14mMdHY0be

    /iaI8fB/Ios7lFiuQ4tv4Wwukg+DUVJVYHNI+JMeJmRLbjburEel

    -----END RSA PRIVATE KEY-----

    '
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 104857600
    expected_clients: 30000
  base_path: /velociraptor
Datastore:
  implementation: FileBaseDataStore
  location: /data
  filestore_directory: /data
  compression: zlib
Logging:
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
obfuscation_nonce: ZmqPXuQeTwI=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
security: {}
